#ifndef IMESHP_F_H
#define IMESHP_F_H

#define IMESHP_VERSION_MAJOR ITAPS_VERSION_MAJOR
#define IMESHP_VERSION_MINOR ITAPS_VERSION_MINOR
#define IMESHP_VERSION_PATCH ITAPS_VERSION_PATCH
#define IMESHP_MAJOR_VERSION IMESHP_VERSION_MAJOR
#define IMESHP_MINOR_VERSION IMESHP_VERSION_MINOR
#define IMESHP_PATCH_VERSION IMESHP_VERSION_PATCH
#define IMESHP_VERSION_GE(Maj,Min,Pat) ITAPS_VERSION_GE(Maj,Min,Pat)
#define IMESHP_VERSION_STRING ITAPS_VERSION_STRING_(iMeshP)
#define IMESHP_VERSION_TAG ITAPS_VERSION_TAG_(iMeshP)
#define IMESHP_NEW_MESH_NAME__(A,B,C) A##_##B##_##C
#define IMESHP_NEW_MESH_NAME_(A,B,C) IMESHP_NEW_MESH_NAME__(A,B,C)
#define IMESHP_NEW_MESH_NAME(A) IMESHP_NEW_MESH_NAME_(A,IMESHP_VERSION_MAJOR,IMESHP_VERSION_MINOR)

#define iMeshP_PartitionHandle IBASE_HANDLE_T
#define iMeshP_RequestHandle IBASE_HANDLE_T

#endif

      integer  iMeshP_EntStatus_MIN
      integer  iMeshP_INTERNAL
      integer  iMeshP_EntStatus_MAX

      parameter(iMeshP_EntStatus_MIN=0)
      parameter(iMeshP_INTERNAL=0)
      parameter(iMeshP_EntStatus_MAX=0)

