#
# This makefile can be used without using autoconf,
# as long as you have IMESH_DIR set to the location
# of the IMESH implementation you're using and 
# F77, FC, CC, and CXX point to the appropriate compilers
#

include ${IMESH_DEFS}
IMESH_INSTALL_DIR=`echo $(IMESH_DEFS) | rev | cut -d'/' -f3- | rev`
IMESH_RPATH_FLAGS=`echo $(IMESH_LIBS) | tr ' ' '\n' | grep -e -L | sed -e 's|-L|-Wl,-rpath,|'`

EXECS = perfF77 perfF90 perfC perfCXX
EXECSOBJ = ${EXECS:=.o}
EXECSOUT = ${EXECS:=.out}
EXECSERR = ${EXECS:=.err}

PERFARGS = 5 I

##   temporary fix until all codes use IMESH_CPPFLAGS
IMESH_INCS=${IMESH_INCLUDES} ${IMESH_CPPFLAGS}

default: ${EXECS}

perfF77: perfF77.o perfF_build.o
	${F77} -o $@ $^ ${IMESH_LIBS} ${EXTRA_F77_LIBS} ${IMESH_RPATH_FLAGS}

perfF90: perfF90.o perfF_build.o
	${FC} -o $@ $^ ${IMESH_LIBS} ${EXTRA_FC_LIBS} ${IMESH_RPATH_FLAGS}

perfC: perfC.o
	${CC} -o $@ $^ ${IMESH_LIBS} ${EXTRA_CC_LIBS} ${IMESH_RPATH_FLAGS}

perfCXX: perfCXX.o
	${CXX} -o $@ $^ ${IMESH_LIBS} ${EXTRA_CXX_LIBS} ${IMESH_RPATH_FLAGS}

.SUFFIXES: .F90 .F .c .cpp

.F90.o:
	${FC} -c -fcray-pointer ${IMESH_FCFLAGS} ${IMESH_INCS} ${FCFLAGS} $<

.F.o:
	${F77} -c -fcray-pointer ${IMESH_FFLAGS} ${IMESH_INCS} ${FFLAGS} $<

.c.o:
	${CC} -g -c ${IMESH_CFLAGS} ${IMESH_INCS} ${CFLAGS} $<

.cpp.o:
	${CXX} -c ${IMESH_CXXFLAGS} ${IMESH_INCS} ${CXXFLAGS} $<

check: default
	./perfF77 $(PERFARGS) 1>perfF77.out 2>perfF77.err
	!(test -s perfF77.err && cat perfF77.err)
	./perfF90 $(PERFARGS) 1>perfF90.out 2>perfF90.err
	!(test -s perfF90.err && cat perfF90.err)
	./perfC $(PERFARGS) 1>perfC.out 2>perfC.err
	!(test -s perfC.err && cat perfC.err)
	./perfCXX $(PERFARGS) 1>perfCXX.out 2>perfCXX.err
	!(test -s perfCXX.err && cat perfCXX.err)

clean:
	rm -f ${EXECS} ${EXECSOBJ} ${EXECSOUT} ${EXECSERR} perfF_build.o

install:
	-install ${EXECS} ${IMESH_INSTALL_DIR}/bin
