#ifndef IGEOM_F_H
#define IGEOM_F_H

#define IGEOM_VERSION_MAJOR ITAPS_VERSION_MAJOR
#define IGEOM_VERSION_MINOR ITAPS_VERSION_MINOR
#define IGEOM_VERSION_PATCH ITAPS_VERSION_PATCH
#define IGEOM_VERSION_GE(Maj,Min,Pat) ITAPS_VERSION_GE(Maj,Min,Pat)
#define IGEOM_VERSION_STRING ITAPS_VERSION_STRING_(iGeom)
#define IGEOM_VERSION_TAG ITAPS_VERSION_TAG_(iGeom)
#define IGEOM_NEW_GEOM_NAME__(A,B,C) A##_##B##_##C
#define IGEOM_NEW_GEOM_NAME_(A,B,C) IGEOM_NEW_GEOM_NAME__(A,B,C)
#define IGEOM_NEW_GEOM_NAME(A) IGEOM_NEW_GEOM_NAME_(A,IGEOM_VERSION_MAJOR,IGEOM_VERSION_MINOR)

#define iGeom_Instance IBASE_HANDLE_T

#endif
